const GET_MY_TAXI_VEHICULES = 'GET_MY_TAXI_VEHICULES';
const GET_MY_TAXI_VEHICULES_SUCCESS = 'GET_MY_TAXI_VEHICULES_SUCCESS';
const GET_MY_TAXI_VEHICULES_FAIL = 'GET_MY_TAXI_VEHICULES_FAIL';

export {
  GET_MY_TAXI_VEHICULES,
  GET_MY_TAXI_VEHICULES_SUCCESS,
  GET_MY_TAXI_VEHICULES_FAIL,
};
