const GET_CAR_2_GO_VEHICULES = 'GET_CAR_2_GO_VEHICULES';
const GET_CAR_2_GO_VEHICULES_SUCCESS = 'GET_CAR_2_GO_VEHICULES_SUCCESS';
const GET_CAR_2_GO_VEHICULES_FAIL = 'GET_CAR_2_GO_VEHICULES_FAIL';

export {
  GET_CAR_2_GO_VEHICULES,
  GET_CAR_2_GO_VEHICULES_SUCCESS,
  GET_CAR_2_GO_VEHICULES_FAIL,
};
